### ISSUE TITLE
Global Disable/Enable

### ISSUE THREAD

**Issue by ConnorVG** [namuol/cheet.js#18]
It would be extremely beneficial if there was  global `disable` / `enable` functionality. Such as:
1) You have a bunch of `cheet` codes;
2) A form opens up;
3) You type X or Y and accidentally activate `cheet` code Z.

Currently, as far as I am aware, you have to disable each cheat individually. This makes it a pain to handle this.

**Comment by ConnorVG** [comment]
@namuol ?

**Comment by namuol** [comment]
Have you tried using `cheet.reset()` inside a global `cheet.next` handler?

i.e. 

```js
var cheetEnabled = true;
function disableCheet() {
  cheetEnabled = true;
}

function enableCheet() {
  cheetEnabled = false;
}

cheet.next(function(sequenceName) {
  if (!cheetEnabled) {
    cheet.reset(sequenceName);
  }
});
```

I'm pretty sure this :point_up: will achieve what you need, so I'm closing this issue. Thanks! 🙇

**Comment by ConnorVG** [comment]
That is an awful workaround 😂

**Comment by namuol** [comment]
> That is an awful workaround 😂

You're welcome :)
